//! A flat, alphabetized catalog of every function name recognized by
//! [`crate::eval::call_function`] plus the handful of names handled as
//! special cases directly in [`crate::eval::eval`] (the composite/adaptive
//! integration rules, `bisect`/`secant`, and `hex`/`oct`/`bin`), each paired
//! with its documented parameter names.
//!
//! This is used by the REPL (see [`crate::repl`]) for both function-name
//! Tab completion and the argument-name hints/navigation shown inside a
//! call's parentheses. The names are kept honest by
//! `tests/function_catalog.rs`, which scans the `eval.rs`/`integration.rs`
//! source text for match-arm string literals and fails the build if this
//! list and the actual dispatch code drift apart in either direction. The
//! argument names are kept honest by `tests/function_arg_hints.rs`, which re-scrapes
//! the `` `name(args)` `` signatures documented in `docs/functions/*.md`
//! (falling back to a documented alias's signature for alias names like
//! `avg`/`prod`/`gauss`) rather than being hand-invented.
//!
//! A trailing `"..."` argument entry marks a variadic tail (e.g.
//! `average(a, b, ...)`).
pub const FUNCTIONS: &[(&str, &[&str])] = &[
    ("abs", &["x"]),
    ("acos", &["x"]),
    ("acosd", &["x"]),
    ("acosh", &["x"]),
    ("acot", &["x"]),
    ("acoth", &["x"]),
    ("acsc", &["x"]),
    ("acsch", &["x"]),
    ("aliquot", &["n"]),
    ("amicable?", &["n"]),
    ("asec", &["x"]),
    ("asech", &["x"]),
    ("asin", &["x"]),
    ("asind", &["x"]),
    ("asinh", &["x"]),
    ("atan", &["x"]),
    ("atan2", &["y", "x"]),
    ("atand", &["x"]),
    ("atanh", &["x"]),
    ("average", &["a", "b", "..."]),
    ("avg", &["a", "b", "..."]),
    ("bell", &["n"]),
    ("beta", &["a", "b"]),
    ("bin", &["n"]),
    ("binom", &["n", "k"]),
    ("binomialcdf", &["n", "p", "k"]),
    ("binomialpdf", &["n", "p", "k"]),
    ("bisect", &["expr", "var", "a", "b", "tolerance"]),
    ("bitlen", &["n"]),
    ("bitreverse", &["n", "width"]),
    ("bman", &["x", "y", "n"]),
    ("boole", &["expr", "var", "a", "b", "n"]),
    ("bth", &["x", "y", "n"]),
    ("c2f", &["c"]),
    ("carmichael", &["n"]),
    ("catalan", &["n"]),
    ("cbrt", &["x"]),
    ("ceil", &["x"]),
    ("chi", &["x"]),
    ("ci", &["x"]),
    ("circlearea", &["r"]),
    ("circumference", &["r"]),
    ("clamp", &["x", "lo", "hi"]),
    ("coprime?", &["a", "b"]),
    ("correlation", &["x1", "y1", "x2", "y2", "..."]),
    ("cos", &["x"]),
    ("cosd", &["x"]),
    ("cosh", &["x"]),
    ("cot", &["x"]),
    ("coth", &["x"]),
    ("covariance", &["x1", "y1", "x2", "y2", "..."]),
    ("csc", &["x"]),
    ("csch", &["x"]),
    ("cterm", &["rate", "futureValue", "presentValue"]),
    ("dawson", &["x"]),
    ("db", &["cost", "salvage", "life", "period", "month"]),
    ("ddb", &["cost", "salvage", "life", "period"]),
    ("deg", &["x"]),
    ("derangement", &["n"]),
    ("digitalroot", &["n"]),
    ("digitsum", &["n"]),
    ("dilog", &["x"]),
    ("distance", &["a...", "b..."]),
    ("dot", &["a...", "b..."]),
    ("eind", &["n"]),
    ("ellipticce", &["k"]),
    ("ellipticck", &["k"]),
    ("elliptice", &["k"]),
    ("ellipticf", &["k"]),
    ("elliptick", &["k"]),
    ("erf", &["x"]),
    ("erfc", &["x"]),
    ("f2c", &["f"]),
    ("factorial", &["n"]),
    ("fermat", &["k"]),
    ("fib", &["n"]),
    ("fibonacci", &["n"]),
    ("floor", &["x"]),
    ("floordiv", &["a", "b"]),
    ("frac", &["x"]),
    ("fresnelc", &["x"]),
    ("fresnelf", &["x"]),
    ("fresnelg", &["x"]),
    ("fresnels", &["x"]),
    ("ft2m", &["ft"]),
    ("fv", &["payment", "rate", "term"]),
    ("fval", &["rate", "nper", "pmt", "pv", "ptype"]),
    ("gamma", &["x"]),
    ("gauss", &["expr", "var", "a", "b", "tolerance"]),
    ("gcd", &["a", "b", "..."]),
    ("genmers", &["m"]),
    ("harmonic", &["n"]),
    ("hex", &["n"]),
    ("hexagonal", &["n"]),
    ("hypot", &["x", "y"]),
    ("int", &["expr", "var", "a", "b", "tolerance"]),
    ("intg", &["x"]),
    ("ipaymt", &["rate", "per", "nper", "pv", "fv", "ptype"]),
    ("irate", &["nper", "pmt", "pv", "fv", "ptype"]),
    ("isqrt", &["n"]),
    ("jacobi", &["a", "n"]),
    ("kg2lb", &["kg"]),
    ("km2mi", &["km"]),
    ("kurtosis", &["a", "b", "..."]),
    ("lb2kg", &["lb"]),
    ("lcm", &["a", "b", "..."]),
    ("lerp", &["a", "b", "t"]),
    ("ln", &["x"]),
    ("log", &["x"]),
    ("log2", &["x"]),
    ("logn", &["x", "b"]),
    ("lucas", &["n"]),
    ("m2ft", &["m"]),
    ("manhattan", &["a...", "b..."]),
    ("max", &["a", "b", "..."]),
    ("median", &["a", "b", "..."]),
    ("mersenne", &["p"]),
    ("mersennegen", &["n"]),
    ("mersgen", &["p"]),
    ("mi2km", &["mi"]),
    ("min", &["a", "b", "..."]),
    ("mod2", &["a", "b"]),
    ("mode", &["a", "b", "..."]),
    ("moebius", &["n"]),
    ("multinomial", &["n", "k1", "k2", "..."]),
    ("newton", &["expr", "var", "a", "b", "n"]),
    ("nextprime", &["n"]),
    ("norm", &["v..."]),
    ("normalcdf", &["x", "mean", "sd"]),
    ("normalpdf", &["x", "mean", "sd"]),
    ("not", &["x"]),
    ("nper", &["rate", "pmt", "pv", "fv", "ptype"]),
    ("npv", &["rate", "cashflow1", "cashflow2", "..."]),
    ("nthroot", &["x", "n"]),
    ("oct", &["n"]),
    ("order", &["a", "n"]),
    ("ordersix", &["expr", "var", "a", "b", "n"]),
    ("ordresix", &["expr", "var", "a", "b", "n"]),
    ("palindrome?", &["n"]),
    ("paymt", &["rate", "nper", "pv", "fv", "ptype"]),
    ("pentagonal", &["n"]),
    ("percentile", &["p", "a", "b", "..."]),
    ("perfect", &["n"]),
    ("perm", &["n", "r"]),
    ("phi", &["n"]),
    ("pmt", &["principal", "rate", "term"]),
    ("pochhammer", &["x", "n"]),
    ("poissoncdf", &["lambda", "k"]),
    ("poissonpdf", &["lambda", "k"]),
    ("popcount", &["n"]),
    ("ppaymt", &["rate", "per", "nper", "pv", "fv", "ptype"]),
    ("prime?", &["n"]),
    ("primec", &["n"]),
    ("primen", &["n"]),
    ("primorial", &["n"]),
    ("prod", &["a", "b", "..."]),
    ("product", &["a", "b", "..."]),
    ("pv", &["payment", "rate", "term"]),
    ("pval", &["rate", "nper", "pmt", "fv", "ptype"]),
    ("rad", &["x"]),
    ("random", &["x"]),
    ("rate", &["futureValue", "presentValue", "term"]),
    ("round", &["x"]),
    ("roundto", &["x", "n"]),
    ("safeprime", &["n"]),
    ("sec", &["x"]),
    ("secant", &["expr", "var", "x0", "x1", "tolerance"]),
    ("sech", &["x"]),
    ("shl", &["x", "y"]),
    ("shr", &["x", "y"]),
    ("si", &["x"]),
    ("sigma", &["n", "k"]),
    ("sign", &["x"]),
    ("simpson", &["expr", "var", "a", "b", "n"]),
    ("sin", &["x"]),
    ("sind", &["x"]),
    ("sinh", &["x"]),
    ("skewness", &["a", "b", "..."]),
    ("sln", &["cost", "salvage", "life"]),
    ("spherearea", &["r"]),
    ("spherevol", &["r"]),
    ("sqrt", &["x"]),
    ("ssi", &["x"]),
    ("stddev", &["a", "b", "..."]),
    ("stirling1", &["n", "k"]),
    ("stirling2", &["n", "k"]),
    ("sum", &["a", "b", "..."]),
    ("syd", &["cost", "salvage", "life", "period"]),
    ("tan", &["x"]),
    ("tand", &["x"]),
    ("tanh", &["x"]),
    ("tau", &["n"]),
    ("term", &["payment", "rate", "futureValue"]),
    ("trapez", &["expr", "var", "a", "b", "n"]),
    ("trapezoid", &["expr", "var", "a", "b", "n"]),
    ("trapezoide", &["expr", "var", "a", "b", "n"]),
    ("triangular", &["n"]),
    ("triarea", &["a", "b", "c"]),
    ("trunc", &["x"]),
    ("variance", &["a", "b", "..."]),
    ("weddle", &["expr", "var", "a", "b", "n"]),
    ("zscore", &["x", "mean", "sd"]),
];

/// Just the function names, for Tab completion.
pub fn function_names() -> impl Iterator<Item = &'static str> {
    FUNCTIONS.iter().map(|(name, _)| *name)
}
